version: '3.8'

services:
  web:
    build: .
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=django_app
      - DATABASE_USER=django_user
      - DATABASE_PASSWORD=password
    env_file:
      - ./.env
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: django_app
      MYSQL_USER: django_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
