# Use the official Python image
FROM python:3.9-slim

# Set work directory
WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

COPY wait-for-it.sh /wait-for-it.sh

# Expose port
EXPOSE 8000

# Run the application
CMD ["/wait-for-it.sh", "db:3306", "--","python", "manage.py", "runserver", "0.0.0.0:8000"]
